version: '3.4'
services:
  dike-mariadb:
    image: 'mariadb:10.3'
    container_name: dike-mariadb
    hostname: dike-mariadb
    ports:
        - "3306:3306"
    volumes:
      - dike-mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aqivMN1WqCjIORXI
      - MYSQL_DATABASE=dike_development
      - MYSQL_USER=dike-mariadb
      - MYSQL_PASSWORD=9GFRsVIr5L7ORVPy

  dike:
    build:
      context: .
      args:
        ROCKET_ENV: development
        ENV: development
    image: dike
    container_name: dike
    ports:
      - "8000:80"
    env_file: .env
    depends_on:
      - dike-mariadb

volumes:
  dike-mariadb-data:
