version: '3.4'
services:
  knock_knock:
    build:
      context: .
      args:
        ROCKET_ENV: $ROCKET_ENV
        ENV: $ENV
    container_name: 'knock_knock'
    image: 'knock_knock'
    ports:
      - "8000:8000"
    env_file: .env
    volumes:
      - ./:/app
    depends_on:
      - "datastore"

  datastore:
    image: 'mariadb:10.3'
    container_name: 'datastore'
    ports:
        - "3306:3306"
    volumes:
      - datastore_volume:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=knock_knock_development
      - MYSQL_USER=datastore_user
      - MYSQL_PASSWORD=9GFRsVIr5L7ORVPy
      - VIRTUAL_HOST=datastore_host

volumes:
  datastore_volume:
