version: '3.4'
services:
  knock-mariadb:
    image: 'mariadb:10.3'
    container_name: knock-mariadb
    hostname: knock-mariadb
    ports:
        - "3306:3306"
    volumes:
      - knock-mariadb-data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=aqivMN1WqCjIORXI
      - MYSQL_DATABASE=knock_development
      - MYSQL_USER=knock-mariadb
      - MYSQL_PASSWORD=9GFRsVIr5L7ORVPy

  knock-knock:
    build:
      context: .
      args:
        ROCKET_ENV: development
        ENV: development
    image: knock-knock
    container_name: knock-knock
    ports:
      - "8000:80"
    env_file: .env
    depends_on:
      - knock-mariadb

volumes:
  knock-mariadb-data:
